/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTutorialRouteImport } from './routes/_authenticated.tutorial'
import { Route as AuthenticatedRecetasRouteImport } from './routes/_authenticated.recetas'
import { Route as AuthenticatedProgresoRouteImport } from './routes/_authenticated.progreso'
import { Route as AuthenticatedPlanRouteImport } from './routes/_authenticated.plan'
import { Route as AuthenticatedPaywallRouteImport } from './routes/_authenticated.paywall'
import { Route as AuthenticatedLoncheraRouteImport } from './routes/_authenticated.lonchera'
import { Route as AuthenticatedHoyRouteImport } from './routes/_authenticated.hoy'
import { Route as AuthenticatedHijosRouteImport } from './routes/_authenticated.hijos'
import { Route as AuthenticatedComprasRouteImport } from './routes/_authenticated.compras'
import { Route as AuthenticatedAjustesRouteImport } from './routes/_authenticated.ajustes'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated.admin'
import { Route as AuthenticatedRecetasIndexRouteImport } from './routes/_authenticated.recetas.index'
import { Route as AuthenticatedRecetasSlugRouteImport } from './routes/_authenticated.recetas.$slug'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTutorialRoute = AuthenticatedTutorialRouteImport.update({
  id: '/tutorial',
  path: '/tutorial',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRecetasRoute = AuthenticatedRecetasRouteImport.update({
  id: '/recetas',
  path: '/recetas',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProgresoRoute = AuthenticatedProgresoRouteImport.update({
  id: '/progreso',
  path: '/progreso',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPlanRoute = AuthenticatedPlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPaywallRoute = AuthenticatedPaywallRouteImport.update({
  id: '/paywall',
  path: '/paywall',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLoncheraRoute = AuthenticatedLoncheraRouteImport.update({
  id: '/lonchera',
  path: '/lonchera',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHoyRoute = AuthenticatedHoyRouteImport.update({
  id: '/hoy',
  path: '/hoy',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHijosRoute = AuthenticatedHijosRouteImport.update({
  id: '/hijos',
  path: '/hijos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedComprasRoute = AuthenticatedComprasRouteImport.update({
  id: '/compras',
  path: '/compras',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAjustesRoute = AuthenticatedAjustesRouteImport.update({
  id: '/ajustes',
  path: '/ajustes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRecetasIndexRoute =
  AuthenticatedRecetasIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedRecetasRoute,
  } as any)
const AuthenticatedRecetasSlugRoute =
  AuthenticatedRecetasSlugRouteImport.update({
    id: '/$slug',
    path: '/$slug',
    getParentRoute: () => AuthenticatedRecetasRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/legal': typeof LegalRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/ajustes': typeof AuthenticatedAjustesRoute
  '/compras': typeof AuthenticatedComprasRoute
  '/hijos': typeof AuthenticatedHijosRoute
  '/hoy': typeof AuthenticatedHoyRoute
  '/lonchera': typeof AuthenticatedLoncheraRoute
  '/paywall': typeof AuthenticatedPaywallRoute
  '/plan': typeof AuthenticatedPlanRoute
  '/progreso': typeof AuthenticatedProgresoRoute
  '/recetas': typeof AuthenticatedRecetasRouteWithChildren
  '/tutorial': typeof AuthenticatedTutorialRoute
  '/recetas/$slug': typeof AuthenticatedRecetasSlugRoute
  '/recetas/': typeof AuthenticatedRecetasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/legal': typeof LegalRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/ajustes': typeof AuthenticatedAjustesRoute
  '/compras': typeof AuthenticatedComprasRoute
  '/hijos': typeof AuthenticatedHijosRoute
  '/hoy': typeof AuthenticatedHoyRoute
  '/lonchera': typeof AuthenticatedLoncheraRoute
  '/paywall': typeof AuthenticatedPaywallRoute
  '/plan': typeof AuthenticatedPlanRoute
  '/progreso': typeof AuthenticatedProgresoRoute
  '/tutorial': typeof AuthenticatedTutorialRoute
  '/recetas/$slug': typeof AuthenticatedRecetasSlugRoute
  '/recetas': typeof AuthenticatedRecetasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/legal': typeof LegalRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/ajustes': typeof AuthenticatedAjustesRoute
  '/_authenticated/compras': typeof AuthenticatedComprasRoute
  '/_authenticated/hijos': typeof AuthenticatedHijosRoute
  '/_authenticated/hoy': typeof AuthenticatedHoyRoute
  '/_authenticated/lonchera': typeof AuthenticatedLoncheraRoute
  '/_authenticated/paywall': typeof AuthenticatedPaywallRoute
  '/_authenticated/plan': typeof AuthenticatedPlanRoute
  '/_authenticated/progreso': typeof AuthenticatedProgresoRoute
  '/_authenticated/recetas': typeof AuthenticatedRecetasRouteWithChildren
  '/_authenticated/tutorial': typeof AuthenticatedTutorialRoute
  '/_authenticated/recetas/$slug': typeof AuthenticatedRecetasSlugRoute
  '/_authenticated/recetas/': typeof AuthenticatedRecetasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/legal'
    | '/onboarding'
    | '/reset-password'
    | '/admin'
    | '/ajustes'
    | '/compras'
    | '/hijos'
    | '/hoy'
    | '/lonchera'
    | '/paywall'
    | '/plan'
    | '/progreso'
    | '/recetas'
    | '/tutorial'
    | '/recetas/$slug'
    | '/recetas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/legal'
    | '/onboarding'
    | '/reset-password'
    | '/admin'
    | '/ajustes'
    | '/compras'
    | '/hijos'
    | '/hoy'
    | '/lonchera'
    | '/paywall'
    | '/plan'
    | '/progreso'
    | '/tutorial'
    | '/recetas/$slug'
    | '/recetas'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/legal'
    | '/onboarding'
    | '/reset-password'
    | '/_authenticated/admin'
    | '/_authenticated/ajustes'
    | '/_authenticated/compras'
    | '/_authenticated/hijos'
    | '/_authenticated/hoy'
    | '/_authenticated/lonchera'
    | '/_authenticated/paywall'
    | '/_authenticated/plan'
    | '/_authenticated/progreso'
    | '/_authenticated/recetas'
    | '/_authenticated/tutorial'
    | '/_authenticated/recetas/$slug'
    | '/_authenticated/recetas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  LegalRoute: typeof LegalRoute
  OnboardingRoute: typeof OnboardingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/tutorial': {
      id: '/_authenticated/tutorial'
      path: '/tutorial'
      fullPath: '/tutorial'
      preLoaderRoute: typeof AuthenticatedTutorialRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/recetas': {
      id: '/_authenticated/recetas'
      path: '/recetas'
      fullPath: '/recetas'
      preLoaderRoute: typeof AuthenticatedRecetasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/progreso': {
      id: '/_authenticated/progreso'
      path: '/progreso'
      fullPath: '/progreso'
      preLoaderRoute: typeof AuthenticatedProgresoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/plan': {
      id: '/_authenticated/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof AuthenticatedPlanRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/paywall': {
      id: '/_authenticated/paywall'
      path: '/paywall'
      fullPath: '/paywall'
      preLoaderRoute: typeof AuthenticatedPaywallRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/lonchera': {
      id: '/_authenticated/lonchera'
      path: '/lonchera'
      fullPath: '/lonchera'
      preLoaderRoute: typeof AuthenticatedLoncheraRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/hoy': {
      id: '/_authenticated/hoy'
      path: '/hoy'
      fullPath: '/hoy'
      preLoaderRoute: typeof AuthenticatedHoyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/hijos': {
      id: '/_authenticated/hijos'
      path: '/hijos'
      fullPath: '/hijos'
      preLoaderRoute: typeof AuthenticatedHijosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/compras': {
      id: '/_authenticated/compras'
      path: '/compras'
      fullPath: '/compras'
      preLoaderRoute: typeof AuthenticatedComprasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ajustes': {
      id: '/_authenticated/ajustes'
      path: '/ajustes'
      fullPath: '/ajustes'
      preLoaderRoute: typeof AuthenticatedAjustesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/recetas/': {
      id: '/_authenticated/recetas/'
      path: '/'
      fullPath: '/recetas/'
      preLoaderRoute: typeof AuthenticatedRecetasIndexRouteImport
      parentRoute: typeof AuthenticatedRecetasRoute
    }
    '/_authenticated/recetas/$slug': {
      id: '/_authenticated/recetas/$slug'
      path: '/$slug'
      fullPath: '/recetas/$slug'
      preLoaderRoute: typeof AuthenticatedRecetasSlugRouteImport
      parentRoute: typeof AuthenticatedRecetasRoute
    }
  }
}

interface AuthenticatedRecetasRouteChildren {
  AuthenticatedRecetasSlugRoute: typeof AuthenticatedRecetasSlugRoute
  AuthenticatedRecetasIndexRoute: typeof AuthenticatedRecetasIndexRoute
}

const AuthenticatedRecetasRouteChildren: AuthenticatedRecetasRouteChildren = {
  AuthenticatedRecetasSlugRoute: AuthenticatedRecetasSlugRoute,
  AuthenticatedRecetasIndexRoute: AuthenticatedRecetasIndexRoute,
}

const AuthenticatedRecetasRouteWithChildren =
  AuthenticatedRecetasRoute._addFileChildren(AuthenticatedRecetasRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAjustesRoute: typeof AuthenticatedAjustesRoute
  AuthenticatedComprasRoute: typeof AuthenticatedComprasRoute
  AuthenticatedHijosRoute: typeof AuthenticatedHijosRoute
  AuthenticatedHoyRoute: typeof AuthenticatedHoyRoute
  AuthenticatedLoncheraRoute: typeof AuthenticatedLoncheraRoute
  AuthenticatedPaywallRoute: typeof AuthenticatedPaywallRoute
  AuthenticatedPlanRoute: typeof AuthenticatedPlanRoute
  AuthenticatedProgresoRoute: typeof AuthenticatedProgresoRoute
  AuthenticatedRecetasRoute: typeof AuthenticatedRecetasRouteWithChildren
  AuthenticatedTutorialRoute: typeof AuthenticatedTutorialRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAjustesRoute: AuthenticatedAjustesRoute,
  AuthenticatedComprasRoute: AuthenticatedComprasRoute,
  AuthenticatedHijosRoute: AuthenticatedHijosRoute,
  AuthenticatedHoyRoute: AuthenticatedHoyRoute,
  AuthenticatedLoncheraRoute: AuthenticatedLoncheraRoute,
  AuthenticatedPaywallRoute: AuthenticatedPaywallRoute,
  AuthenticatedPlanRoute: AuthenticatedPlanRoute,
  AuthenticatedProgresoRoute: AuthenticatedProgresoRoute,
  AuthenticatedRecetasRoute: AuthenticatedRecetasRouteWithChildren,
  AuthenticatedTutorialRoute: AuthenticatedTutorialRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  LegalRoute: LegalRoute,
  OnboardingRoute: OnboardingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
declare module '@tanstack/react-router' {
  interface Register {
    router: ReturnType<typeof getRouter>
  }
}
